name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
  repository_dispatch:
    types: [ run_build ]

jobs:
  ci:
    name: Run CI on ${{ matrix.config.name }}
    runs-on: ubuntu-24.04
    env:
      CC: ${{ matrix.config.cc }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "gcc 12",   cc: gcc-12 }
          - { name: "gcc 13",   cc: gcc-13 }
          - { name: "gcc 14",   cc: gcc-14 }
          - { name: "clang 16", cc: clang-16 }
          - { name: "clang 17", cc: clang-17 }
          - { name: "clang 18", cc: clang-18 }

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libsdl2-dev libavcodec-dev libavformat-dev libavutil-dev \
            libswresample-dev libswscale-dev libass-dev clang-tidy ${{ matrix.config.cc }}

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DUSE_TIDY=1 -DBUILD_EXAMPLES=1 ..
          make -j2
